### ISSUE TITLE
If a key is required == false then the key shouldn't have to even exist in the .config file.

### ISSUE THREAD

**Issue by PureKrome** [luisrudge/configurator#6]
Give this example:

`var myKey = config.Get<string>("MyKey", false);`

this _currently_ does the following:

- get the value of the key, from the file. NOTE: THE KEY/VALUE MUST EXIST.
- if there is no value, then contintue cause the _value_ is optional.

I think this would be better if the KEY is also optional.

So this means the following:

Old code:

```
EnsureKeyExists(key);
var value = ConfigurationManager.AppSettings[key];
```

New code:

```
string value;
if (required)
{
    EnsureKeyExists(key);
    value = ConfigurationManager.AppSettings[key];
}
```

Note: not sure how this would work for a ENUM though. Anyways, you get the idea.

Happy to create a PR, etc.

**Comment by luisrudge** [comment]
Not sure what's the use case behind this. Can you explain why would you want to bypass the key checking?

**Comment by PureKrome** [comment]
Yep - sure.

I had an optional key/value for localhost (eg. AppInsights) but wanted the key/value for dev/prod. So for localhost I had to create an empty value.

In my code, i have a check to see if the value is something, then use it.

So, was just a thought.

**Comment by luisrudge** [comment]
So, something like this?

```csharp
var appInsightsId = config.Get<string>("appInsights", false);
if (appInsightsId != null) {
  EnableAppInsights(appInsightsId);
}
```

**Comment by PureKrome** [comment]
Yeah - that's sorta what I am doing right now. I still would have to do that.

It's just that I don't have to add the key/value to my localhost webconfig file.

Playing devil's advocate, all environments should have the same number of key/values .. so maybe the current code is a good thing?

**Comment by luisrudge** [comment]
That's why I built it like this. You can already do what you want like this:

```csharp
var appInsightsId = config.GetOrDefault<string>("appInsights", null);
if (appInsightsId != null) {
  EnableAppInsights(appInsightsId);
}
```

**Comment by PureKrome** [comment]
AH! `Get` vs `GetorDefault` 

Case closed :)

**Comment by luisrudge** [comment]
I added an example in the readme on how to use GetOrDefault. 🎉

**Comment by PureKrome** [comment]
Awesome! thank you sir!
